version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: ./cmd/bot/Dockerfile
    container_name: bot
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - NATS_HOST=${NATS_HOST}
      - NATS_PORT=${NATS_PORT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./data/bot:/data
    restart: always
    depends_on:
      - postgres
      - nats
  reminder:
    build:
      context: .
      dockerfile: ./cmd/reminder/Dockerfile
    container_name: reminder
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - NATS_HOST=${NATS_HOST}
      - NATS_PORT=${NATS_PORT}
    restart: always
    depends_on:
      - postgres
      - nats
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
  nats:
    image: nats:2.6.2-alpine
    container_name: nats
    ports:
      - "${NATS_PORT}:4222"
    restart: always

