version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./cmd/bot/Dockerfile
    depends_on:
      - db
      - nats
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@db:5432/remindmebot?sslmode=disable
      - NATS_URL=nats://nats:4222
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pkg/postgres/migrations:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats:
    image: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"

